---
title: "ART Survival Analysis"
output: 
  html_document:
    keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r load-packages, echo = FALSE, message=F,output=F}
knitr::opts_chunk$set(echo = F)
library(VISCfunctions)
library(tidyverse)
library(here)
library(glue)
library(kableExtra)
library(GGally)
library(cowplot)
library(survival)
library(survminer)
theme_set(theme_bw() + theme(legend.position = "top", panel.grid.minor = element_blank()))

source(here("R", "directory-funs.R"))

rx_lab = tibble(
  rx_code2 = c("C", "T1", "T2"),
  trt_cat = c("Placebo", "VRC01 (10mg/kg)", "VRC01 (30mg/kg)")
)

time_lab = "Days post-first positive"



```

```{r load-data}

vl_data = read_csv(clean_data_here("adata-vl.csv"), col_types = cols())

art_surv_data = vl_data %>%
  group_by(pub_id) %>%
  mutate(last_day = max(days_enrollment),
         last_day_fp = max(days_fp)
         ) %>%
  ungroup() %>%
  distinct(pub_id, rx_code2, protocol, any_art, art_day, fp_day, last_day, last_day_fp) %>%
  mutate(
    time_to_art = if_else(any_art, art_day - fp_day, last_day_fp),
    time_to_art_check = if_else(any_art, art_day - fp_day, last_day -fp_day),
    grp = factor(rx_code2, levels = rx_lab$rx_code2, labels= rx_lab$trt_cat)
    )

stopifnot(all(art_surv_data$time_to_art > 0))
stopifnot(all(art_surv_data$time_to_art == art_surv_data$time_to_art_check))

```

```{r sample-sizes}

art_surv_data %>%
  group_by(protocol, grp) %>%
  summarize(N = n_distinct(pub_id), .groups = "drop") %>%
  pivot_wider(values_from = N, names_from = grp) %>%
  janitor::adorn_totals() %>%
  kable() %>%
  kable_styling(full_width = F)
```

```{r sample-size-endpoints}

art_surv_data %>%
  group_by(protocol, any_art, grp) %>%
  summarize(N = n_distinct(pub_id), `.groups` = "drop") %>%
  pivot_wider(values_from = N, names_from = grp) %>%
  janitor::adorn_totals() %>%
  kable() %>%
  kable_styling(full_width = F)

```


```{r pooled, fig.height=7}

surv_pool = survfit(Surv(time_to_art, any_art) ~ grp, data = art_surv_data)
names(surv_pool$strata) <- gsub("grp=", "", names(surv_pool$strata)) 
# pairwise_survdiff(Surv(time_to_art, any_art) ~ rx_code2, data = art_surv_data) 
# loc_lr_pvalues = as_tibble(round(ada_surv_loc_test[["p.value"]], 2), rownames = " ") %>%
#   replace_na(list(`Left Arm` = " "))

ggsurvplot(
  surv_pool,
  data = art_surv_data,
  legend.title = "",
  risk.table = T,
  palette = c("black", "blue", "red"),
  ylab = "Cumulative incidence",
  xlab = time_lab,
  fun = "event"
) 


# ci_fit <- 
#   cmprsk::cuminc(
#     ftime = art_surv_data$time_to_art, 
#     fstatus = art_surv_data$any_art, 
#     group = as.numeric(art_surv_data$grp),
#     cencode = 0
#     )
# ggcompetingrisks(ci_fit, xlab = "Days", multiple_panels = FALSE)

```

```{r amp703, fig.height=7}


surv_703 = survfit(Surv(time_to_art, any_art) ~ grp, 
                   data = subset(art_surv_data, protocol == "HVTN 703"))
names(surv_703$strata) <- gsub("grp=", "", names(surv_703$strata)) 

#pairwise_survdiff(Surv(time_to_art, any_art) ~ grp, data = subset(art_surv_data, protocol == "HVTN 703"))

pl_703 = ggsurvplot(
  surv_703,  
  risk.table = T,
  palette = c("black", "blue", "red"),
  data = subset(art_surv_data, protocol == "HVTN 703"),
  legend.title = "",
  ylab = "Cumulative incidence",
  xlab = time_lab,
  fun = "event",
  ylim = c(0, 1)
) +
  ggtitle("HVTN703")

pl_703

```

```{r amp704, fig.height=7}


surv_704 = survfit(Surv(time_to_art, any_art) ~ grp, 
                   data = subset(art_surv_data, protocol == "HVTN 704"))
names(surv_704$strata) <- gsub("grp=", "", names(surv_704$strata)) 

#pairwise_survdiff(Surv(time_to_art, any_art) ~ grp, data = subset(art_surv_data, protocol == "HVTN 704"), p.adjust.method = "none")

pl_704 = ggsurvplot(
  surv_704,
  risk.table = T,
  data = subset(art_surv_data, protocol == "HVTN 704"),
  palette = c("black", "blue", "red"),
  legend.title = "",
  ylab = "Cumulative incidence",
  xlab = time_lab,
  fun = "event",
  ylim = c(0, 1)
) +
  ggtitle("HVTN704")

pl_704
```

```{r inc-both}

plot_grid(nrow = 2, rel_heights = c(12,2),
          plot_grid(pl_703$plot + theme(legend.position = "none"), 
                    pl_704$plot + theme(legend.position = "none")),
          get_legend(pl_703$plot)
)

```



```{r, eval = F}

ada_surv_summary_loc = ada_surv %>%
  group_by(loc = infusion_location_1) %>% summarize(mean_pct = round_away_0(100*mean(event == 1)))

ada_surv_fit_loc = survfit(Surv(ada_study_day, event) ~ infusion_location_1, data = ada_surv) 
ada_surv_loc_test = pairwise_survdiff(Surv(ada_study_day, event) ~ infusion_location_1, data = ada_surv, p.adjust.method = "none") 


names(ada_surv_fit_loc$strata) <- gsub("infusion_location_1=", "", names(ada_surv_fit_loc$strata)) 
loc_lr_pvalues = as_tibble(round(ada_surv_loc_test[["p.value"]], 2), rownames = " ") %>%
  replace_na(list(`Left Arm` = " "))

loc_surv_pl = ggsurvplot(ada_surv_fit_loc, data = ada_surv, risk.table = T, legend.title = "", 
                         xlab = "Visit day post administration")
loc_surv_pl$plot = loc_surv_pl$plot +
  ggpp::annotate("table", x = 0, y = 0.2, label = list(loc_lr_pvalues), vjust = 1, hjust = 0) +
  ggplot2::annotate("text", x = 0, y = 0.21, label = "Log-rank p-value", vjust = 0, hjust = 0)

loc_surv_pl

```
