---
title: "First positive regression analysis"
author: "Bryan Mayer"
date: "`r Sys.Date()`"
output: 
  html_document:
    keep_md: true
    code_folding: hide
---

```{r load-packages, echo = FALSE, message=F,output=F,warning=F}
knitr::opts_chunk$set(echo = T)
library(VISCfunctions)
library(tidyverse)
library(here)
library(glue)
library(kableExtra)
library(GGally)
library(cowplot)
library(emmeans)
library(drtmle)
library(janitor)
library(cowplot)
library(knitr)
source(here("R", "directory-funs.R"))
source(here("R", "vl-regression-funs.R"))

table_tag = "tables/fp-"

theme_set(theme_bw() + theme(legend.position = "top", panel.grid.minor = element_blank(), panel.grid.major = element_blank()))

opts_chunk$set(dev = c("png", "pdf"))

#stopifnot(dir.exists("/Volumes/trials/"))

vl_lims = c(1, 7)
vl_title = expression(paste("Viral load (log"[10], " copies/mL)"))
ep_labels = tibble(
  levels = c("fp", "peak", "nadir", "mean"),
  label = c("First positive", "Peak", "Nadir", "Mean")
)

rx_labeller = tibble(
  rx_code2 = c("C", "T1", "T2"),
  trt_cat = c("Placebo", "VRC01 (10mg/kg)", "VRC01 (30mg/kg)")
)

final_model = 'lm'

ic80gte1_colors = c(`IC80 < 1 mcg/mL` = "#008080", `IC80 >= 1 mcg/mL` = "coral")
protocol_colors = c(`HVTN 703/HPTN 085` = "magenta", `HVTN 704/HPTN 081` = "purple")

```

```{r child="0-vl-regression-data-setup.Rmd", echo = T}
```

# First positive analysis

```{r box-fp-by-protocol}
data_plots[["first_positive"]][["prot_pl"]]
```

```{r box-fp-by-region}
data_plots[["first_positive"]][["region_pl"]]
```

```{r box-fp-trt}
data_plots[["first_positive"]][["trt_pl"]]
```

```{r box-fp-trt-pool}
data_plots[["first_positive"]][["trt_pl_pool"]]
```


```{r fp-run-models}
trt_grp_fp = run_vl_drtmle_glm(mdata = first_positive, A_var = "rx_code", trt_map = rx_map, run_lm = T)
trt_grp_pool_fp = run_vl_drtmle_glm(mdata = first_positive, A_var = "rx_pool_code", trt_map = rx_pool_map, run_lm = T)
trt_ic80_fp = run_vl_drtmle_glm(mdata = first_positive, A_var = "trt_ic80_code", trt_map = trt_grp_map, run_lm = T)
trt_ic80_pool_fp = run_vl_drtmle_glm(mdata = first_positive, A_var = "trt_ic80_pool_code", trt_map = trt_pool_map, run_lm = T)

fp_models = lst(trt_grp_fp, trt_grp_pool_fp, trt_ic80_fp, trt_ic80_pool_fp)
```

## Mean first positive viral loads

```{r fp-mm-table-pool}

trt_ic80_pool_fp[['mm']] %>%
    filter(model == final_model) %>%
    mutate(mean_ci = stat_paste(est, cil, ciu, digits = 2)) %>%
  select(`Group` = trt_var, `Mean First Positive (95pct CI)` = mean_ci) %>%
  write_csv(paste0(table_tag, "pool-means.csv")) %>%
  kable(caption = "Marginal means for first RNA+ log$_{10}$ viral load. estimates adjusted for protocol/region.", format = "html") %>%
  kable_styling(full_width = F)

```

```{r fp-mm-fig-pool}

trt_ic80_pool_fp[['mm']] %>%
  filter(model == final_model) %>%
  ggplot(aes(
    x = trt_var,
    y = est,
    ymin = cil,
    ymax = ciu
  )) +
  geom_pointrange(position = position_dodge(width = 0.5)) +
  labs(y = "Mean first positive log10 viral load (95% CI)", x = "VRC01 Groups") +
  scale_y_continuous(limits = c(2.5, 6.25)) +
  coord_flip()

```

```{r fp-mm-table}

map2_df(fp_models, names(fp_models), ~ (
  .x[['mm']] %>%
    filter(model == final_model) %>%
    mutate(mean_ci = stat_paste(est, cil, ciu, digits = 2), model_set = .y) 
)) %>% 
  mutate(
    sens = if_else(str_detect(model_set, "ic80"), "Modification", "Not included"),
    trt_set = if_else(str_detect(model_set, "pool"), "Pooled", "All doses")
  ) %>%
  select(`Viral sensitivity` = sens, `VRC01 Grouping` = trt_set, `Group` = trt_var, `Mean (95pct CI)` = mean_ci) %>%
  kable(caption = "Marginal means for first RNA+ log$_{10}$ viral load. estimates adjusted for protocol/region.", format = "html") %>%
  kable_styling(full_width = F) %>%
  collapse_rows(1:2, valign = "top")

```

```{r fp-mm-plots}

fp_mm_pls = map(fp_models, ~(
  .[['mm']] %>%
  filter(model == final_model) %>%
  ggplot(aes(x = trt_var, y = est, ymin = cil, ymax = ciu)) +
    geom_pointrange(position = position_dodge(width = 0.5)) +
    labs(y = "Mean first positive log10 viral load (95% CI)", x = "VRC01 Groups") +
    scale_y_continuous(limits = c(2.5, 6.1)) +
    coord_flip()
))

plot_grid(plotlist = fp_mm_pls)

```

## Group comparisons

```{r fp-comp-pool-table}

trt_ic80_pool_fp[['contrast']] %>%
    filter(model == final_model) %>%
    mutate(
      mean_ci = stat_paste(est, cil, ciu, digits = 2), 
      p.value = pretty_pvalues(p.value)
  ) %>%
  select(`Comparison` = contrast, `Mean First Positive Diff. (95pct CI)` = mean_ci, `p-value` = p.value) %>%
  write_csv(paste0(table_tag, "pool-comp.csv")) %>%
  kable(caption = "Differences in first RNA+ log$_{10}$ viral load. Estimates adjusted for protocol/region.", 
        format = "html",
        digits = 3) %>%
  kable_styling(full_width = F)

```


```{r fp-comp-pool-figure}

trt_ic80_pool_fp[['contrast']] %>%
  filter(model == final_model) %>%
  ggplot(aes(x = contrast, y = est, ymin = cil, ymax = ciu)) +
    geom_pointrange(position = position_dodge(width = 0.5)) +
    geom_hline(yintercept = 0, linetype = "dashed", colour = "red") +
    labs(y = "Difference first positive log10 viral load (95% CI)", x = "") +
    coord_flip() +
  theme(axis.text.y = element_text(size = 8))

```

```{r fp-comp-table}

map2_df(fp_models, names(fp_models), ~ (
  .x[['contrast']] %>%
    filter(model == final_model) %>%
    mutate(
      mean_ci = stat_paste(est, cil, ciu, digits = 2), 
      model_set = .y,
      p.value = pretty_pvalues(p.value)) 
)) %>% 
  mutate(
    sens = if_else(str_detect(model_set, "ic80"), "Modification", "Not included"),
    trt_set = if_else(str_detect(model_set, "pool"), "Pooled", "All doses")
  ) %>%
  select(`Viral sensitivity` = sens, `VRC01 Grouping` = trt_set, `Comparison` = contrast, `Mean Diff. (95pct CI)` = mean_ci, `p-value` = p.value) %>%
  kable(caption = "Differences in first RNA+ log$_{10}$ viral load. Estimates adjusted for protocol/region.", 
        format = "html",
        digits = 3) %>%
  kable_styling(full_width = F) %>%
  collapse_rows(1:2, valign = "top")

```

```{r fp-comp-plots, fig.height = 11}

fp_contrast_pls = map(fp_models, ~(
  .[['contrast']] %>%
  filter(model == final_model) %>%
  ggplot(aes(x = contrast, y = est, ymin = cil, ymax = ciu)) +
    geom_pointrange(position = position_dodge(width = 0.5)) +
    geom_hline(yintercept = 0, linetype = "dashed", colour = "red") +
    labs(y = "Difference first positive log10 viral load (95% CI)", x = "") +
    coord_flip()
))

plot_grid(plotlist = fp_contrast_pls, ncol = 1)

```

## Protocol/Region Comparisons

```{r fp-protocol-comp}

map2_df(fp_models, names(fp_models), ~ (
  .x[['protocol_contrast']] %>%
    mutate(
      mean_diff = round_away_0(est, digits = 3), 
      model_set = .y,
      p.value = pretty_pvalues(p.value)) 
)) %>% 
  mutate(
    sens = if_else(str_detect(model_set, "ic80"), "Modification", "Not included"),
    trt_set = if_else(str_detect(model_set, "pool"), "Pooled", "All doses")
  ) %>%
  select(`Viral sensitivity` = sens, `VRC01 Grouping` = trt_set, `Comparison` = contrast, `Mean Diff.` = mean_diff, `p-value` = p.value) %>%
    write_csv(paste0(table_tag, "protocol-region-comparison.csv")) %>%
kable(caption = "Differences in first RNA+ log$_{10}$ viral load between protocol/region groups.", 
        format = "html",
        digits = 3) %>%
  kable_styling(full_width = F) %>%
  collapse_rows(1:2, valign = "top")

```

# Appendix

```{r drtmle-data-setup, eval = final_model!="lm"}

first_positive %>%
  tabyl(rx_lab, rx_code) %>%
  kable() %>%
  kable_styling(full_width= F)

first_positive %>%
  tabyl(rx_pool, rx_pool_code) %>%
  kable() %>%
  kable_styling(full_width= F)

first_positive %>%
  tabyl(trt_ic80, trt_ic80_code) %>%
  kable() %>%
  kable_styling(full_width= F)

first_positive %>%
  tabyl(trt_ic80_pool, trt_ic80_pool_code) %>%
  kable() %>%
  kable_styling(full_width= F)
```