library(renv)
init(bare = T)

settings$ignored.packages("lixoftConnectors")
install("purrr@0.3.5")
install("rlang@1.1.0")
install("dbplyr@2.1.1")
install("dplyr@1.0.10")
install("googlesheets4@0.3.0")
install("knitr@1.40")
install("tidyverse@1.3.1")
install("testthat@3.1.5")
install("zoo")
install("glue@1.6.2")
remotes::install_github("haozhu233/kableExtra")
install("ggbeeswarm@0.6.0")
install("cowplot@1.1.1")
install("usethis@2.1.6")
install("here@1.0.1")
install("pkr@0.1.3")
install("ggbeeswarm@0.6.0")
install("viridis@0.6.2")
install("GGally@2.1.2")
install("janitor@2.1.0")
install("table1@1.4.2")
install("flextable@0.8.3")
install("survminer@0.4.9")
install("emmeans@1.7.0")
install("drtmle@1.1.1")

install("Rsmlx@5.0.1")

install("rmarkdown")
install("patchwork@1.2.0")

remotes::install_version("dparser", version = '1.3.1.4')
remotes::install_version("PreciseSums", version = '0.4')
install("RxODE@1.1.5")
remotes::install_github("FredHutch/VISCfunctions")

install("git2r@0.31.0")
install.packages(c("htmlTable", "interp", "matrixStats", "polyclip",
                   "rootSolve", "s2", "TH.data"))

snapshot()

