---
title: "Processing viral load data"
author: "Bryan Mayer"
date: "3/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(usethis)
library(here)
library(lubridate)
source(here("R", "directory-funs.R"))

# -------- processing functions --------

diffdays = function(x, y) as.numeric(difftime(mdy(x), mdy(y), units = "days"))

# note that censor_flag == -1 denoted upper censoring (so a positive still)
find_firstpositive = function(censor_flag, dates){
  if(!any(censor_flag != 1)) return(NA_character_)
  pos_dates = dates[censor_flag != 1]
  # a character in this format is consistent with other date variables in the raw data
  as.character(format(min(mdy(pos_dates)), '%m-%d-%Y'))
}

```

## Background

Combining and cleaning the raw VL data. Main challenges are managing time and censoring.

Note: The neutralization data comes from the same set of data but was simpler to process.


```{r load-raw}

v703_vl = read_csv(raw_data_here("AMP Data for Modeling files/v703_viral_loads_blinded.csv"))
v704_vl = read_csv(raw_data_here("AMP Data for Modeling files/v704_viral_loads_blinded.csv"))
raw_vl = bind_rows(v703_vl, v704_vl)

rx_dat = read_csv(raw_data_here('rx_dat.csv'))

dans_data = read_csv(raw_data_here("DR-amp-vl-blinded.csv"))


```



Checking raw vl data with other data

```{r data-checks}

n_distinct(raw_vl$pub_id)

x = read_csv(raw_data_here("AMP Data for Modeling files/amp_survival_wk80_tau_neut_blinded.csv")) %>% dplyr::filter(!is.na(nisolates))
n_distinct(x$pub_id)
infected_ids = rx_dat %>% dplyr::filter(pub_id %in% x$pub_id) %>% select(pub_id) %>% unlist() %>% unname()

# all infections are in the vl data
setdiff(infected_ids, unique(raw_vl$pub_id))

# missing neuts
all_neut = intersect(infected_ids, unique(subset(x, !is.na(gmt80ls))$pub_id))

# 46 ptids are in the viral load data sets but were not assayed for neutralization (also not counted as infected in NEJM)
odd_ids = setdiff(unique(raw_vl$pub_id), infected_ids)
dplyr::filter(rx_dat, pub_id %in% setdiff(unique(raw_vl$pub_id), infected_ids))
test = subset(raw_vl, pub_id %in% odd_ids)
```


```{r process-data}

# three mutates:
# 1) cleaning the variables
# 2) by pub_id, get the first positive date
# 3) subsequent day/time calculations

final_vl_data = raw_vl %>%
  dplyr::select(-MITT_flag, -statuswk104, -statuswk80, -assaytyp, -result, -resultc, -comments) %>%
  mutate(
    study = if_else(protocol == "HVTN 703", 1, 2),
    infection_pre80wks = !pub_id %in% odd_ids,
    has_neut_data = pub_id %in% all_neut,
    cens = if_else(str_detect(vl, ">"), -1, if_else(str_detect(vl, "<"), 1, 0)),
    vl_num = parse_number(vl)
  ) %>%
  group_by(pub_id) %>%
  mutate(
    fpdt = find_firstpositive(cens, drawdt),
    any_art = any(!is.na(artstartdt))
  ) %>%
  ungroup() %>%
  mutate(
    on_art = if_else(!is.na(artstartdt), as.numeric(diffdays(drawdt, artstartdt) >= 0), 0),
    art_day = if_else(!is.na(artstartdt), diffdays(artstartdt,dxdt), Inf),
    dx_day = diffdays(dxdt, enrdt),
    fp_day = diffdays(fpdt, enrdt),
    est_inf_day = diffdays(est, enrdt),
    dx_post_inf = diffdays(dxdt, est),
    fp_post_inf = diffdays(fpdt, est),
    days_enrollment = diffdays(drawdt, enrdt),
    days_dx = diffdays(drawdt, dxdt),
    days_fp = diffdays(drawdt, fpdt),
    days_infection = diffdays(drawdt, est)
  )
```


```{r data-dx}

final_vl_data %>% distinct(pub_id, infection_pre80wks, has_neut_data) %>%
  group_by(infection_pre80wks, has_neut_data) %>% summarize(n())

test_inftime = final_vl_data %>%
  #dplyr::filter(is.na(est)) %>%
  distinct(pub_id, flag, est, dxdt, dx_post_inf, has_neut_data)

test_inftime %>%
  group_by(flag, has_neut_data) %>%
  summarize(n())

ggplot(test_inftime, aes(x = flag, y = dx_post_inf, colour = factor(has_neut_data))) + geom_point() +
  coord_flip() + theme(axis.text.y = element_text(size = 4))

final_vl_data %>%
  dplyr::filter(dxdt == drawdt & raw_vl == "<20") %>%
  distinct(pub_id, flag, est, dxdt, dx_post_inf, has_neut_data)

subset(final_vl_data, pub_id == "703-0203") %>%
  select(days_dx, days_fp, days_infection, days_enrollment, on_art)
subset(dans_data, pid == "703-0203")

```

```{r save-dat, eval = T}
write_csv(final_vl_data, file = clean_data_here("full_vl_data.csv"))
```

