---
title: "Survival Analysis for Various Time-based Outcomes"
output: 
  html_document:
    keep_md: true
---

```{r load-packages, echo = FALSE, message=F,output=F}
knitr::opts_chunk$set(echo = F)
library(VISCfunctions)
library(tidyverse)
library(here)
library(glue)
library(kableExtra)
library(GGally)
library(cowplot)
library(survival)
library(survminer)
library(knitr)
theme_set(theme_bw() + theme(legend.position = "top", panel.grid.minor = element_blank()))

source(here("R", "directory-funs.R"))

rx_lab = tibble(
  levels = c("C", "T1", "T2"),
  trt_cat = c("Placebo", "VRC01 (10mg/kg)", "VRC01 (30mg/kg)")
)

time_lab_inf = "Weeks post final infusion (pre-RNA+)"
time_lab_fp = "Weeks post first RNA+"
#colors = c('gray','light green','forest green')
colors = c('gray40','steelblue','navy')
color_protocol = c("magenta", "purple")


ic80gte1_colors = c(`IC80 < 1 mcg/mL` = "#1F77B4", `IC80 >= 1 mcg/mL` = "coral")
ic80_label = c(`IC80 < 1 mcg/mL` =  bquote("#1F77B4"),
               `IC80 >= 1 mcg/mL` =  "coral"
             )

ytitle_fp = "Cumulative fraction first RNA+"
ytitle_art = "Cumulative fraction ART initiation"
opts_chunk$set(dev = c("png", "pdf"))

```

```{r load-data}

time_summary_data = read_csv(clean_data_here("adata-time-summary.csv"), col_types = cols()) %>%
  mutate(
    protocol_full = if_else(protocol == "HVTN 703", "HVTN 703/HPTN 081", "HVTN 704/HPTN 085")
    )

```

## ART Incidence Curves

```{r}

art_surv_data = time_summary_data %>%
  dplyr::filter() %>%
  mutate(
    any_art = !is.na(artstartdt),
    time_to_art = if_else(any_art, art_day - fp_day, final_day - fp_day)/7,
    grp = rx_lab,
    ic80gte1 = factor(gmt80ls >= 1, levels = c(F, T), 
                      labels = c("IC80 < 1 mcg/mL", "IC80 >= 1 mcg/mL")),
    )

stopifnot(all(art_surv_data$time_to_art > 0))
stopifnot(all(!is.na(art_surv_data$any_art)))

```

```{r sample-sizes}

art_surv_data %>%
  group_by(protocol_full, grp) %>%
  summarize(N = n_distinct(pub_id), .groups = "drop") %>%
  pivot_wider(values_from = N, names_from = grp) %>%
  janitor::adorn_totals() %>%
  kable() %>%
  kable_styling(full_width = F)
```

```{r sample-size-endpoints}

art_surv_data %>%
  group_by(protocol_full, any_art, grp) %>%
  summarize(N = n_distinct(pub_id), `.groups` = "drop") %>%
  pivot_wider(values_from = N, names_from = grp) %>%
  janitor::adorn_totals() %>%
  kable() %>%
  kable_styling(full_width = F)

```


```{r pooled, fig.height=7}

surv_pool = survfit(Surv(time_to_art, any_art) ~ grp, data = art_surv_data)
names(surv_pool$strata) <- gsub("grp=", "", names(surv_pool$strata)) 
# pairwise_survdiff(Surv(time_to_art, any_art) ~ rx_code2, data = art_surv_data) 
# loc_lr_pvalues = as_tibble(round(ada_surv_loc_test[["p.value"]], 2), rownames = " ") %>%
#   replace_na(list(`Left Arm` = " "))

ggsurvplot(
  surv_pool,
  data = art_surv_data,
  legend.title = "",
  risk.table = T,
  palette = colors,
  ylab = ytitle_art,
  xlab = time_lab_fp,
  fun = "event"
) 


# ci_fit <- 
#   cmprsk::cuminc(
#     ftime = art_surv_data$time_to_art, 
#     fstatus = art_surv_data$any_art, 
#     group = as.numeric(art_surv_data$grp),
#     cencode = 0
#     )
# ggcompetingrisks(ci_fit, xlab = "Days", multiple_panels = FALSE)

```

```{r amp703-art-tbl, fig.height=7}

surv_703 = survfit(Surv(time_to_art, any_art) ~ grp, 
                   data = subset(art_surv_data, protocol == "HVTN 703"))
names(surv_703$strata) <- gsub("grp=", "", names(surv_703$strata)) 

pairwise_survdiff(Surv(time_to_art, any_art) ~ grp, data = subset(art_surv_data, protocol == "HVTN 703"), p.adjust.method = "none")

pl_703 = ggsurvplot(
  surv_703,  
  risk.table = T,
  palette = colors,
  data = subset(art_surv_data, protocol == "HVTN 703"),
  legend.title = "",
  ylab = ytitle_art,
  xlab = time_lab_fp,
  fun = "event",
  ylim = c(0, 1)
) +
  ggtitle("HVTN 703/HPTN 081")

pl_703

```

```{r amp704-art-tbl, fig.height=7}

surv_704 = survfit(Surv(time_to_art, any_art) ~ grp, 
                   data = subset(art_surv_data, protocol == "HVTN 704"))
names(surv_704$strata) <- gsub("grp=", "", names(surv_704$strata)) 

pairwise_survdiff(Surv(time_to_art, any_art) ~ grp, data = subset(art_surv_data, protocol == "HVTN 704"), p.adjust.method = "none")

pl_704 = ggsurvplot(
  surv_704,
  risk.table = T,
  data = subset(art_surv_data, protocol == "HVTN 704"),
  palette = colors,
  legend.title = "",
  ylab = ytitle_art,
  xlab = time_lab_fp,
  fun = "event",
  ylim = c(0, 1)
) +
  ggtitle("HVTN 704/HPTN 085")

pl_704
```


```{r art-protocol-tbl}

surv_protocol = survfit(Surv(time_to_art, any_art) ~ protocol_full, 
                   data = art_surv_data)
names(surv_protocol$strata) <- gsub("protocol_full=", "", names(surv_protocol$strata)) 

pairwise_survdiff(Surv(time_to_art, any_art) ~ protocol_full, data = art_surv_data, p.adjust.method = "none")

pl_protocol = ggsurvplot(
  surv_protocol,
  risk.table = T,
  data = art_surv_data,
  palette = color_protocol,
  legend.title = "",
  ylab = ytitle_art,
  xlab = time_lab_fp,
  fun = "event",
  ylim = c(0, 1)
) 

pl_protocol

```

```{r art-ic80-tbl}

surv_ic80 = survfit(Surv(time_to_art, any_art) ~ ic80gte1, 
                   data = art_surv_data)
names(surv_ic80$strata) <- str_remove(names(surv_ic80$strata), "ic80gte1=") 

pairwise_survdiff(Surv(time_to_art, any_art) ~ ic80gte1, data = art_surv_data, p.adjust.method = "none")

pl_ic80 = ggsurvplot(
  surv_ic80,
  risk.table = T,
  data = art_surv_data,
  palette = c("#008080", "coral"),
  legend.title = "",
  ylab = ytitle_art,
  xlab = time_lab_fp,
  fun = "event",
  ylim = c(0, 1)
) 

pl_ic80


```

```{r inc-art-trt}

plot_grid(nrow = 2, rel_heights = c(12,2),
          plot_grid(pl_703$plot + theme(legend.position = "none"), 
                    pl_704$plot + theme(legend.position = "none")),
          get_legend(pl_703$plot)
)

```


```{r inc-art-protocol, fig.width = 4}

pl_protocol$plot + theme(legend.position = "bottom", legend.text = element_text(size = 9))

```


```{r inc-art-ic80, fig.width = 4}

pl_ic80$plot + theme(legend.position = "bottom")

```


## Last infusion (pre positive RNA) to first positive


```{r setup-fp}

subset(time_summary_data, is.na(final_infusion_day))
stopifnot(all(!is.na(time_summary_data$fp_day) & time_summary_data$fp_day < Inf))
stopifnot(all(!is.na(time_summary_data$final_infusion_pre_fp_day) & time_summary_data$final_infusion_pre_fp_day < Inf))
any(is.na(time_summary_data$fp_day))

fp_surv_data = time_summary_data %>%
  dplyr::filter() %>%
  mutate(
    time_to_fp = (fp_day - final_infusion_pre_fp_day)/7,
    grp = rx_lab,
    ic80gte1 = factor(gmt80ls >= 1, levels = c(F, T), 
                      labels = c("IC80 < 1 mcg/mL", "IC80 >= 1 mcg/mL"))
    )


```




```{r fp-pooled, fig.height=7}

fp_surv_pool = survfit(Surv(time_to_fp) ~ grp, data = fp_surv_data)
names(fp_surv_pool$strata) <- gsub("grp=", "", names(fp_surv_pool$strata)) 
pairwise_survdiff(Surv(time_to_fp) ~ grp, data = fp_surv_data, p.adjust.method = "none")
# loc_lr_pvalues = as_tibble(round(ada_surv_loc_test[["p.value"]], 2), rownames = " ") %>%
#   replace_na(list(`Left Arm` = " "))

ggsurvplot(
  fp_surv_pool,
  data = fp_surv_data,
  legend.title = "",
  risk.table = T,
  palette = colors,
  ylab = ytitle_fp,
  xlab = time_lab_inf,
  fun = "event"
) 


# ci_fit <- 
#   cmprsk::cuminc(
#     ftime = art_surv_data$time_to_art, 
#     fstatus = art_surv_data$any_art, 
#     group = as.numeric(art_surv_data$grp),
#     cencode = 0
#     )
# ggcompetingrisks(ci_fit, xlab = "Days", multiple_panels = FALSE)

```

```{r fp-amp703, fig.height=7}

fp_surv_703 = survfit(Surv(time_to_fp) ~ grp, 
                   data = subset(fp_surv_data, protocol == "HVTN 703"))
names(fp_surv_703$strata) <- gsub("grp=", "", names(fp_surv_703$strata)) 

pairwise_survdiff(Surv(time_to_fp) ~ grp, data = subset(fp_surv_data, protocol == "HVTN 703"), p.adjust.method = "none")

fp_pl_703 = ggsurvplot(
  fp_surv_703,  
  risk.table = T,
  palette = colors,
  data = subset(fp_surv_data, protocol == "HVTN 703"),
  legend.title = "",
  ylab = ytitle_fp,
  xlab = time_lab_inf,
  fun = "event",
  ylim = c(0, 1),
  font.x = c(12),
  xlim = c(0, 80),
  break.x.by = 20
) +
  ggtitle("HVTN 703/HPTN 081")

fp_pl_703

```

```{r fp-amp704, fig.height=7}

fp_surv_704 = survfit(Surv(time_to_fp) ~ grp, 
                   data = subset(fp_surv_data, protocol == "HVTN 704"))
names(fp_surv_704$strata) <- gsub("grp=", "", names(fp_surv_704$strata)) 

pairwise_survdiff(Surv(time_to_fp) ~ grp, data = subset(fp_surv_data, protocol == "HVTN 704"), p.adjust.method = "none")

fp_pl_704 = ggsurvplot(
  fp_surv_704,
  risk.table = T,
  data = subset(fp_surv_data, protocol == "HVTN 704"),
  palette = colors,
  legend.title = "",
  ylab = ytitle_fp,
  xlab = time_lab_inf,
  fun = "event",
  font.x = c(12),
  ylim = c(0, 1)
) +
  ggtitle("HVTN 704/HPTN 085")

fp_pl_704

```


```{r fp-protocol}

fp_surv_protocol = survfit(Surv(time_to_fp) ~ protocol_full, 
                   data = fp_surv_data)
names(fp_surv_protocol$strata) <- gsub("protocol_full=", "", names(fp_surv_protocol$strata)) 

pairwise_survdiff(Surv(time_to_fp) ~ protocol_full, data = fp_surv_data, p.adjust.method = "none")

fp_pl_protocol = ggsurvplot(
  fp_surv_protocol,
  risk.table = T,
  data = fp_surv_data,
  palette = color_protocol,
  legend.title = "",
  ylab = ytitle_fp,
  xlab = time_lab_inf,
  fun = "event",
  ylim = c(0, 1)
) 

fp_pl_protocol

```

```{r fp-ic80}

fp_surv_ic80 = survfit(Surv(time_to_fp) ~ ic80gte1, data = fp_surv_data)
names(fp_surv_ic80$strata) <- str_remove(names(fp_surv_ic80$strata), "ic80gte1=") 

pairwise_survdiff(Surv(time_to_fp) ~ ic80gte1, data = fp_surv_data, p.adjust.method = "none")

fp_pl_ic80 = ggsurvplot(
  fp_surv_ic80,
  risk.table = T,
  data = fp_surv_data,
  palette = c("#008080", "coral"),
  legend.title = "",
  ylab = ytitle_fp,
  xlab = time_lab_inf,
  fun = "event",
  ylim = c(0, 1)
) 

fp_pl_ic80


```

```{r inc-fp-trt}

plot_grid(nrow = 2, rel_heights = c(12,2),
          plot_grid(fp_pl_703$plot + theme(legend.position = "none"), 
                    fp_pl_704$plot + theme(legend.position = "none")),
          get_legend(fp_pl_704$plot)
)

```


```{r inc-fp-protocol, fig.width = 4}

fp_pl_protocol$plot + theme(legend.position = "bottom", legend.text = element_text(size = 11))

```


```{r inc-fp-ic80, fig.width = 4}

fp_pl_ic80$plot + theme(legend.position = "bottom")

```



