---
title: "AMP Placebo + RV217 viral loads - Monolix modeling"
author: "Bryan Mayer"
date: "`r Sys.Date()`"
output: 
  html_document:
    keep_md: true
---



```{r load-packages, echo = FALSE, message=F,output=F}
knitr::opts_chunk$set(echo = F)
library(VISCfunctions)
library(tidyverse)
library(here)
library(glue)
library(kableExtra)
library(lixoftConnectors)
library(ggPMX)
library(GGally)

theme_set(theme_bw() + theme(legend.position = "top"))

options(scipen = 999)

initializeLixoftConnectors(software = "monolix")

# plot cutoff
cutoff = 1.602060
cutoffexp = substitute(expression(NULL <= a), list(a = cutoff))

# timing_parms %>% select(-contains("corr")) %>% gather 

```

```{r load-funs-data}

source(here("R", "directory-funs.R"))
source(here("R", "mlx-model-funs.R"))
source(here("R", "mlx-envir-res.R"))
source(here("R", "mlx-res-processing.R"))
source(here("R", "fix-parm-funs.R"))
source(here("R", "mlx-plot-funs.R"))


vl_dir_tag = function(x) paste0("VL/", x)
vl_model_here = function(x, ...) mlx_model_here(vl_dir_tag(x), ...)

```

```{r datatype-setup}
# check_data("ampPlaceboHoltet0-rv217.csv")

vl_pool_types = tribble(
    ~var_name, ~type,
    "pub_id", "id",
    "TIME", "ignore",
    "DV", "observation",
    "DV_log", "ignore",
    "days_fp", "TIME",
    "tpf_est", "ignore",   
    "cens", "cens",
    "limit", "limit",
    "country", "ignore",
    "gmt50ms", "ignore",
    "gmt80ms", "ignore",
    "gmt50ls", "ignore",
    "gmt80ls", "ignore",
    "gmt50mf", "ignore", 
    "gmt80mf", "ignore",
    "nisolates", "ignore",
    "protocol", "catcov",
    "study", "ignore",
    "rx_code2", "ignore",
    "holte_est", "contcov"
  ) 

log10vl_pool_types = tribble(
    ~var_name, ~type,
    "pub_id", "id",
    "TIME", "ignore",
    "DV", "ignore",
    "DV_log", "observation",
    "days_fp", "TIME",
    "tpf_est", "ignore",   
    "cens", "cens",
    "limit", "ignore",
    "country", "ignore",
    "gmt50ms", "ignore",
    "gmt80ms", "ignore",
    "gmt50ls", "ignore",
    "gmt80ls", "ignore",
    "gmt50mf", "ignore", 
    "gmt80mf", "ignore",
    "nisolates", "ignore",
    "protocol", "catcov",
    "study", "ignore",
    "rx_code2", "ignore",
    "holte_est", "contcov"
  ) 

```



```{r model-setup}

# https://onlinelibrary.wiley.com/doi/epdf/10.1111/imr.12698
tcl_priors = tibble(
  aS_pop = 100,
  lBt0_pop = -3,
  dS_pop = 0.1,
  dI_pop = 1,
  lp_pop = log10(250)
)

eff_priors = tibble(
    tau_pop = 0.05,
    k_pop = 0.3,
    w_pop = 1,
    dE_pop = 0.002,
    E50_pop = 1 
)

precursor_priors = tibble(
    f_pop = 0.9,
    k_pop = 1,
    w_pop = 8.5,
    dE_pop = 2.3,
    dP_pop = 0.001,
    NP_pop = 5
)

# https://www.biorxiv.org/content/10.1101/700401v2.full.pdf hill model (Table S1)

parameter_labels = tribble(
  ~parm, ~parameter_label,
  "aS", "alphaS",
  "log10_dS", "log10(deltaS)",
  "dS", "deltaS",
  "lBt0", "log10(beta)",
  "dI", "kappa",
  "log10_dI", "log10(kappa)",
  "n", "h",
  "lp", "log10(pi)",
  "initT", "First pos.- Inf. day"
)

demographics = read_csv(mlx_data_here("ampPlaceboHoltet0-rv217.csv"), col_types = cols()) %>%
  group_by(pub_id) %>%
  mutate(first_pos_day = TIME[days_fp == 0]) %>%
  ungroup() %>%
  dplyr::distinct_at(vars(pub_id, protocol, holte_est, first_pos_day, country, contains("gmt"), nisolates)) %>%
  mutate(protocol2 = if_else(protocol == "RV217", protocol, "AMP"))

```

# Overview

Here, we "train" the population viral load model **on the placebo population + RV217 only**. Infection times were estimated separately using the Holte model and merged on here. 

See math-model-descriptions for further details.

# Models

## Effector

```{r effector-model-free, eval = F}

amp_recipe(
  model_text_file = "Effector_Model.txt",
  data_file = "ampPlaceboHoltet0-rv217.csv",
  variable_types = vl_pool_types,
  initial_estimates = TRUE
  )

setup_effector_parms(bind_cols(tcl_priors, eff_priors))
set_holte_est_infection_times()
getPopulationParameterInformation()

# getPopulationParameterInformation()
runScenario()
setInitialEstimatesToLastEstimates()
set_project_settings(initial_estimates = FALSE)
runScenario()

setIndividualParameterVariability(dS = F, lp = F, dI = F)
runScenario()

setPopulationParameterInformation(
  a = list(initialValue = getEstimatedPopulationParameters()[["a"]], method = "FIXED")
  )

runScenario()
                                  
save_project(vl_dir_tag("effector_amp_holteT0"))

```

```{r effector-pl}

infection_time_spaghetti(vl_dir_tag("effector_amp_holteT0"), 
                         dem_dat = demographics ) +
  facet_wrap(~protocol, nrow = 3)

```

```{r effector-model-fixed-dI, eval = F}

amp_recipe(
  model_text_file = "Effector_Model.txt",
  data_file = "ampPlaceboHoltet0-rv217.csv",
  variable_types = vl_pool_types,
  initial_estimates = TRUE
  )

setup_effector_parms(bind_cols(tcl_priors, eff_priors))
set_holte_est_infection_times()
getPopulationParameterInformation()

setPopulationParameterInformation(
  dI_pop = list(initialValue = 1, method = "FIXED")
)
setIndividualParameterVariability(dI = F)

# getPopulationParameterInformation()
runScenario()
setInitialEstimatesToLastEstimates()
set_project_settings(initial_estimates = FALSE)
runScenario()

setIndividualParameterVariability(w = F, lp = F)
runScenario()

setPopulationParameterInformation(
  a = list(initialValue = getEstimatedPopulationParameters()[["a"]], method = "FIXED")
  )

runScenario()

save_project(vl_dir_tag("effector_amp_holteT0_fixed-dI"))

```

```{r effector-fixedI-pl}

infection_time_spaghetti(vl_dir_tag("effector_amp_holteT0_fixed-dI"), 
                         dem_dat = demographics ) +
  facet_wrap(~protocol, nrow = 3)

```

```{r effector-model-fixed-set, eval = F}

amp_recipe(
  model_text_file = "Effector_Model.txt",
  data_file = "ampPlaceboHoltet0-rv217.csv",
  variable_types = vl_pool_types,
  initial_estimates = TRUE
  )


setup_effector_parms(bind_cols(tcl_priors, eff_priors))
set_holte_est_infection_times()

setPopulationParameterInformation(
  dI_pop = list(initialValue = 0.8, method = "FIXED"),
  lp_pop = list(initialValue = 4.7, method = "FIXED"),
  aS_pop = list(initialValue = 70, method = "FIXED")
)
setIndividualParameterVariability(dI = F, lp = F, aS = F)
getPopulationParameterInformation()

runScenario()
setInitialEstimatesToLastEstimates()
set_project_settings(initial_estimates = FALSE)
runScenario()

setPopulationParameterInformation(
  a = list(initialValue = getEstimatedPopulationParameters()[["a"]], method = "FIXED")
  )

runScenario()

save_project(vl_dir_tag("effector_amp_holteT0_fixed-set"))

```

```{r effector-fixed_set-pl}

infection_time_spaghetti(vl_dir_tag("effector_amp_holteT0_fixed-set"), 
                         dem_dat = demographics ) +
  facet_wrap(~protocol2, nrow = 2)
  
```

## Pre-cursor effector

```{r precursor-effector}

amp_recipe(
  model_text_file = "2_Precursor_Effector_Model.txt",
  data_file = "ampPlaceboHoltet0-rv217.csv",
  variable_types = log10vl_pool_types,
  initial_estimates = TRUE
  )

setObservationDistribution(DV_log = "normal")
setErrorModel(DV_log = "constant")
getContinuousObservationModel()

tcl_priors2 = tibble(
  aS_pop = 3,
  lBt0_pop = -4.5,
  dS_pop = 0.05,
  dI_pop = 0.02,
  lp_pop = 4.5
)

setup_precursor_parms(bind_cols(tcl_priors2, precursor_priors))
set_holte_est_infection_times()
setIndividualParameterVariability(dP = F)
setPopulationParameterInformation(dP_pop = list(method = 'FIXED'))
getPopulationParameterInformation()

runScenario()
setInitialEstimatesToLastEstimates()
set_project_settings(initial_estimates = FALSE)
runScenario()

setIndividualParameterVariability(lp = F)
runScenario()

save_project(vl_dir_tag("precursor_effector_amp_holteT0"))

```

```{r precursor-effector-pl}

infection_time_spaghetti(vl_dir_tag("precursor_effector_amp_holteT0"), 
                         dem_dat = demographics, output_name =  "DV_log") +
  facet_wrap(~protocol, nrow = 3) 

```

## Holte Fits

```{r}

holte_fits = read_csv(here("output/vl-analysis/holte-amp-fits.txt"), col_types = cols()) %>%
  mutate(model = "holte", dv = indivPredMode)

hill_fits = read_csv(here("models/GUI/hill-test/ChartsData/IndividualFits/DV_log_fits.txt"), col_types = cols()) %>%
  mutate(model = "hill", dv = indivPredMode)

eff_fits = read_csv(mlx_model_here(file.path(vl_dir_tag("effector_amp_holteT0_fixed-set"), 
                                             "ChartsData/IndividualFits/DV_fits.txt")), col_types = cols()) %>%
  mutate(model = "effector", dv = log10(pmax(0.01, indivPredMode)))

holte_fits %>%
  bind_rows(eff_fits) %>%
  bind_rows(hill_fits) %>%
  left_join(demographics, by = c("ID" = "pub_id")) %>%
  dplyr::filter(protocol2 == "AMP") %>%
  mutate(infection_days = time + holte_est) %>%
  dplyr::filter(infection_days >= 0 & infection_days < 100) %>%
  ggplot(aes(x = infection_days, y = dv)) +
  scale_y_continuous(limits = c(-2, 8.5), breaks = 1:8) +
  geom_line(aes(group = ID), alpha = 0.25) +
  facet_wrap(~model, nrow = 1)

```

# Results

```{r res-setup, eval = F}

models_loc = list_mlx_models(pool_fit_loc())

time_loc = c(
  "viralload/pooled-models/holte_free",
  "viralload/pooled-models/tcl_free",
  "viralload/timing-estimation/refit_RSIF_placebo_t0"
)

fits = stack_indiv_fits(models_loc) %>%
  mutate(weeks = time / 7) 

ipreds = stack_indiv_ests(models_loc) %>%
  mutate(weeks = time/7) 

parm_fits = stack_indiv_parms(models_loc)

placebo_ids = get_indiv_parms(time_loc[3]) %>% pull(id)

paul_times = read_csv(mlx_data_here("amp-vl-placebo.csv"), col_types = cols()) %>%
  dplyr::distinct(id = pub_id, tinf_est) %>%
  mutate(model = "Paul_est")

time_ests = stack_indiv_parms(time_loc) %>%
  dplyr::select(id, tinf_est = initT_mode, model) %>%
  bind_rows(paul_times)%>%
  mutate(placebo = id %in% placebo_ids)

```

```{r pmx-load, include = F, eval = F}

models_pmx = map(
  models_loc,
  ~ pmx_mlx(
    config = "standing",
    directory = mlx_model_here(.),
    input = mlx_data_here("amp_placebo-rv217-vl.csv"),
    id = "pub_id",
    dv = "DV",
    cats = c("study"),
    settings = pmx_settings(is.draft = FALSE)
  )
) 

```

```{r pop-fits, eval = F}

stack_model_ests(models_loc) %>%
  dplyr::mutate(parameter = if_else(parameter == "OFV", "LogLik", parameter)) %>%
  dplyr::filter(parameter != "V0_pop") %>%
  left_join(mutate(parameter_labels, parm = paste0(parm, "_pop")), by = c("parameter" = "parm")) %>%
  mutate(
    parameter = if_else(parameter == "OFV", "LogLik", parameter),
    parameter_label = if_else(is.na(parameter_label), "", parameter_label),
    value = if_else(parameter == "dS_pop", value*10^4, value),
    parameter = if_else(parameter == "dS_pop", "dS_pop x 10^-4", parameter),
    estimate_rse = if_else(!is.na(rse_sa),
                           stat_paste(value, abs(rse_sa), digits = 2),
                           stat_paste(value, digits = 2)
  )) %>%
  dplyr::select(parameter_label, parameter, estimate_rse, model) %>% 
  pivot_wider(values_from = estimate_rse, names_from = model)  %>%
  #dplyr::select(parameter_label, parameter, contains("omega"), contains("refit")) %>%
  arrange(desc(parameter_label)) %>%
  kable(format = "html", booktabs = TRUE, linesep = "", escape = FALSE,
        caption = "Population parameters (%RSE). RSEs are not estimated for fixed parameters or the error term.") %>%
  kable_styling(full_width = F)

```

```{r indiv-pl, eval = F}
#| message = FALSE, warning=F,
#| fig.width=10, fig.height=15,

ggplot(fits, aes(x = weeks, y = log10(pmax(0.01, indivPredMode)))) +
  geom_point(data = dplyr::filter(ipreds, time > -100),
             aes(y = log10(DV), shape = as.factor(censored != 0))) +
  geom_line(aes(colour = model)) +
  scale_shape_discrete("Below LLoQ") +
  facet_wrap(~ ID, nrow = 16, ncol = 7, scales = "free_x") +
  labs(y = "log10 VL", colour = "", x = "weeks") +
  theme(legend.position = 'top', axis.text.x = element_text(size = 8)) + 
  guides(shape = guide_legend(ncol = 1, nrow = 2))

```


```{r indiv-pl-subset, eval = F}
#| message = FALSE, warning=F,
#| fig.width=8, fig.height=3,

id_set = c("703-0926", "703-1889","704-1706", "704-2981")
fits %>%
  dplyr::filter(ID %in% id_set & model == "tcl_free_holteT0_pool") %>%
  ggplot(aes(x = weeks, y = log10(pmax(1, indivPredMode)))) +
  geom_point(data = dplyr::filter(ipreds, time > -100 & ID %in% id_set),
             aes(y = log10(DV), shape = as.factor(censored != 0))) +
  geom_line() +
  scale_shape_discrete("Below LLoQ") +
  scale_x_continuous(limits = c(-10, NA)) +
  scale_y_continuous(breaks = 1:9, limits = c(1,8)) +
  facet_wrap(~ ID, nrow = 1, scales = "free_x") +
  labs(y = "log10 VL", colour = "", x = "weeks") +
  theme(legend.position = 'none', axis.text.x = element_text(size = 8)) + 
  guides(shape = guide_legend(ncol = 1, nrow = 2))

```

## Parameters

```{r parms, eval = F}
#| message = FALSE, warning=F,
#| fig.width=8, fig.height=3

parm_fits %>%
  dplyr::filter(model == "tcl_free_holteT0_pool") %>%
  pivot_longer(names_to = "parm", values_to = "est", cols = c("aS_mode","dS_mode","lBt0_mode", "dI_mode")) %>%
  mutate(parm = factor(parm, levels = c("aS_mode","dS_mode","lBt0_mode", "dI_mode"),
                       labels = c("alpha", "deltaS", "log10(beta)", "kappa"))) %>%
  ggplot(aes(x = " ", y = est)) +
  geom_boxplot() +
  labs(x = "", y = "") +
  facet_wrap(~parm, nrow = 1, scale = "free_y",  strip.position = "left") +
  theme(strip.background = element_blank(), strip.placement = "outside")


```

## Time ests

```{r cor-plot-1, eval = F}


time_ests %>%
  dplyr::filter(placebo) %>%
  dplyr::select(-placebo) %>%
  pivot_wider(values_from = tinf_est, names_from = model) %>%
  dplyr::select(-id) %>% 
  ggpairs(progress = F, xlab = "First pos - inf time",
           ylab = "First pos - inf time") 


```


```{r cor-plot-2, eval = F}

source(here("R", "time-corplot-funs.R"))

suppressMessages({
  time_ests %>%
    dplyr::filter(placebo) %>%
    dplyr::select(-placebo) %>%
    pivot_wider(values_from = tinf_est, names_from = model) %>%
    dplyr::select(-id) %>%
    ggpairs(
            upper = list(continuous = wrap(my_custom_cor)),
            lower = list(continuous = my_custom_smooth),
            diag = list(continuous = my_boxplot),
            progress = F, xlab = "First pos - inf time",
            ylab = "First pos - inf time") +
  scale_x_continuous(limits = c(0, 75)) +
  scale_y_continuous(limits = c(0, 75))
})

```

# Categorical

```{r placebo-cat-vars, eval = F}
#| message = FALSE, warning=F,
#| fig.width=7,fig.height=7,
#| fig.cap = paste0("Model:", 1:length(models_pmx))

for(i in 1:length(models_pmx)){
  pmx_plot_eta_cats(models_pmx[[i]], labels = list(title = basename(models_loc)[i])) %>%
    print()
}


```


```{r, eval = F}
read_csv(here("models/GUI/holte-test/ChartsData/ObservationsVsPredictions/DV_log_obsVsPred.txt")) %>%
  ggplot(aes(x = indivPredMode, y = DV_log_simBlq_mode)) +
  geom_point() +
  geom_abline()


read_csv("~/Downloads/code/amponly/ChartsData/ObservationsVsPredictions/log10VL_obsVsPred.txt") %>%
  ggplot(aes(x = indivPredMode, y = log10VL_simBlq_mode)) +
  geom_point() +
  geom_abline()


```
